### PR TITLE
ADD FEATURE TO READ FREQUENCIES FROM VASP OUTCAR

### PR DESCRIPTION
**Pull request by himaghna**
- adding "vib_outcar" column in excel, read vibration wavenumbers directly form outcar. read preferentially to wavenumbers written in excel. 
- additional parameter min_frequency_cutoff added to read_excel. Only    wavenumbers>min_frequency_cutoff read from OUTCAR

### CODE REVIEW

**Comment by jonlym** [comment]
Hi @himaghna 

Thanks for adding this new feature. 

- Could you convert your pMuTT.io_.vasp docstrings to use the [numpy format](https://numpydoc.readthedocs.io/en/latest/format.html)? 
- Also, could you write unit tests ([in this folder](https://github.com/VlachosGroup/pMuTT/tree/c06f845fd1d6e4199a34634263e5518471551aaa/pMuTT/tests)) for each of the functions that you've implemented so others can see expected behavior?
- Do we need a try/except block in [pMuTT.io_.read_excel L103](https://github.com/VlachosGroup/pMuTT/blob/c06f845fd1d6e4199a34634263e5518471551aaa/pMuTT/io_/excel.py#L103) and [pMuTT.io_.vasp L57](https://github.com/VlachosGroup/pMuTT/blob/c06f845fd1d6e4199a34634263e5518471551aaa/pMuTT/io_/vasp.py#L57) if the error raised would have been raised by the contents of the try block anyway?

**Comment by himaghna** [comment]
Hi!
Thanks for moderating

- Will do

- Will do

- Error handling in L103 and L57 are just to give the calling function an option of handling the specific error instead of leaving it to fail ungracefully. I could make the messages more verbose

**Comment by wittregr** [comment]
Also, Thanks for your contribution.  I also reviewed your code PEP8
readability requirements. There were a few exceptions which I fixed. Your
IDE should have an automatic scan for PEP8...Turn that on and it makes
compliance easy.

Gerhard R Wittreich, P.E.
Ph.D. Candidate, Vlachos Research Group
Harker ISE Lab-367BJ
Chemical and Biomolecular Engineering, University of Delaware

**Comment by jonlym** [comment]
@himaghna, I realized I pointed to the wrong line for pMuTT.io_.vasp. I meant to point to [line 26](https://github.com/VlachosGroup/pMuTT/blob/c06f845fd1d6e4199a34634263e5518471551aaa/pMuTT/io_/vasp.py#L26).

I see how L26 adds value (but perhaps include the error message in the raise statement rather than a print statement but I think you may have been following my code in [L200](https://github.com/VlachosGroup/pMuTT/blob/c06f845fd1d6e4199a34634263e5518471551aaa/pMuTT/io_/excel.py#L200) so I need to follow my own advice :P). 

However, I still think L103's try/except block is not useful as it extends the traceback and gives the exact same behavior as without the try/except block.

**Pull request merged**
